labels: ['op: melhoria', 'relev: não medida']
body:
  - type: markdown
    attributes:
      value: |
        Descreva os pontos que você quer deixar para melhorar. Descreva suas sugestões para melhoria e observações importantes.
