labels: ['op: melhoria', 'relev: não medida']
body:
  - type: markdown
    attributes:
      value: |
        Descreva os pontos que você quer deixar para melhorar. Descreva suas sugestões para melhoria e observações importantes.
  - type: dropdown
    id: servidor
    attributes:
      label: Servidor afetado
      description: Essa ideia é direcionada para qual área?
      options:
        - Todos
        - Discord
        - Sites ou externos
        - Redes sociais
        - Henesys
        - Vanillew
        - Skyten
        - Lobby
        - Ausevento
        - Um novo servidor
      default: 0
    validations:
      required: true
  - type: textarea
    id: proposito
    attributes:
      label: Descrição
      description: |
        Descreva seus argumentos.
    validations:
      required: true
