name: Bug
description: Reportar um bug ou comportamento equivocado
labels: ['bug: confirmado', '→⚪']
type: 'Bug'
assignees: leogianfagna
body:
  - type: markdown
    attributes:
      value: |
        Confira em responder todos os campos corretamente.
  - type: dropdown
    id: servidor
    attributes:
      label: Servidor referido
      description: Este bug está em qual servidor?
      options:
        - Não especificado (qualquer)
        - Henesys
        - Vanillew
        - Skyten
        - Lobby
        - Ausevento
        - Discord
        - Sites ou externos
        - Redes sociais
        - Um novo servidor
      default: 0
    validations:
      required: true
  - type: textarea
    attributes:
      label: Descrição do bug
      description: Descreva o que ocorreu de forma equivocada.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Reprodução
      description: |
        Descreva detalhamente como reproduzir o bug. Se alguém que denunciou,
        pergunte-o ou peça prints do bug e envie aqui.
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        **Atenção:** Selecione as tags referentes a qual servidor. Caso necessário, altere o responsável por corrigir o bug. Se o bug ainda não foi confirmado, altere o tag para bug não confirmado.
