name: Tarefa
description: Lembrar de fazer algo
labels: ["to-do: ⚪"]
assignees: ["leogianfagna", "Micosedeunha"]
body:
  - type: textarea
    attributes:
      label: Descrição da tarefa
      description: O que precisa ser feito? Você pode enviar arquivos.
    validations:
      required: true
