name: Tarefa
description: Lembrar de fazer algo
labels: ['tarefa']
assignees: ['leogianfagna', 'Micosedeunha', 'Batatoones', 'lemoslucass', 'MathMSilva']
body:
  - type: textarea
    attributes:
      label: Descrição da ideia
      description: Manda a bala aqui com tudo que puder!
    validations:
      required: true
