name: Add Label
on:
  issues:
    types: [opened]

jobs:
  add-label:
    name: Add Label
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: tella-adam/add-labels@v1
        with:
          labels: |
            complexo
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
