name: Add server labels
# https://github.com/marketplace/actions/remove-labels

on:
  issues:
    types: [opened]

permissions:
  issues: write
  pull-requests: write

jobs:
  add-label:
    name: Add Label
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: christianvuerings/add-labels@v1
        with:
          labels: |
            servidor: henesys
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
