name: Label issues
on:
  issues:
    types:
      - reopened
      - opened
jobs:
  label_issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Normalize issue body and determine label
        id: determine_label
        run: |
          # Normaliza o texto para remover quebras de linha e espaços desnecessários
          ISSUE_BODY=$(echo "${{ github.event.issue.body }}" | tr -d '\r' | tr '\n' ' ' | sed 's/  */ /g')
          
          # Procura os padrões específicos no texto normalizado
          # Prioridade
          if echo "$ISSUE_BODY" | grep -qi "Gravidade Baixa"; then
            echo "label=→🟢" >> $GITHUB_ENV
          elif echo "$ISSUE_BODY" | grep -qi "Gravidade Média"; then
            echo "label=→🟡" >> $GITHUB_ENV
          elif echo "$ISSUE_BODY" | grep -qi "Gravidade Alta"; then
            echo "label=→🟠" >> $GITHUB_ENV
          elif echo "$ISSUE_BODY" | grep -qi "Gravidade Urgência total"; then
            echo "label=→🔴" >> $GITHUB_ENV
          
          # Servidores
          if echo "$ISSUE_BODY" | grep -qi "Servidor referido Lobby"; then
            echo "label=sv: lobby" >> $GITHUB_ENV
          elif echo "$ISSUE_BODY" | grep -qi "Servidor referido Vanillew"; then
            echo "label=sv: vanillew" >> $GITHUB_ENV
          elif echo "$ISSUE_BODY" | grep -qi "Servidor referido Ausevento"; then
            echo "label=sv: ausevento" >> $GITHUB_ENV
          elif echo "$ISSUE_BODY" | grep -qi "Servidor referido Skyten"; then
            echo "label=sv: skyten" >> $GITHUB_ENV
          elif echo "$ISSUE_BODY" | grep -qi "Servidor referido Henesys"; then
            echo "label=sv: henesys" >> $GITHUB_ENV
          else
            echo "label=" >> $GITHUB_ENV
          fi
      - name: Add label if determined
        if: env.label != ''
        run: gh issue edit "$NUMBER" --add-label "$LABEL"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          NUMBER: ${{ github.event.issue.number }}
          LABEL: ${{ env.label }}
