name: Add Label for Henesys

on:
  issues:
    types: [opened]

jobs:
  add_label:
    runs-on: ubuntu-latest

    steps:
    - name: Check for henesys in the issue description
      id: check_henesys
      uses: actions/github-script@v6

    - name: Add label if "henesys" is found
      uses: actions-ecosystem/action-add-labels@v1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        labels: 'complexo'
