name: Remove Labels on Issue Close

on:
  issues:
    types: [closed]

jobs:
  remove_labels:
    runs-on: ubuntu-latest
    steps:
      - name: Remove specific labels when issue is closed
        uses: actions-ecosystem/action-remove-labels@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: |
            'status: desenvolvendo'
            'status: arquivado'
            'status: necessita detalhes'
            'status: solução encontrada'
            'status: reportado ao dev'
            'status: buscando mais ideias'
