name: Remove outdated labels

on:
  issues:
    types: [closed]

permissions:
  issues: write
  pull-requests: write

jobs:
  remove-closed-issue-labels:
    name: Remove closed issue labels
    if: github.event.issue.state == 'closed'
    runs-on: ubuntu-latest
    steps:
      - uses: mondeja/remove-labels-gh-action@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          labels: |
            ideia
            complexo
