name: Remove Labels

on:
  issues:
    types: [closed]

jobs:
  remove_labels:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-ecosystem/action-remove-labels@v1.3.0
        with:
          labels: |
            ideia
            "status: desenvolvendo"
