name: Remove Labels on Issue Close

on:
  issues:
    types: [closed]

jobs:
  remove_labels:
    runs-on: ubuntu-latest
    steps:
      - name: Remove specific labels when issue is closed
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          labels=("status: desenvolvendo" "status: arquivado" "status: necessita detalhes" "status: solução encontrada" "status: reportado ao dev" "status: buscando mais ideias")
          issue_number="${{ github.event.issue.number }}"
          repo="${{ github.repository }}"
          
          for label in "${labels[@]}"; do
            curl -X DELETE \
              -H "Authorization: token $GITHUB_TOKEN" \
              -H "Accept: application/vnd.github.v3+json" \
              "https://api.github.com/repos/$repo/issues/$issue_number/labels/$label"
          done
