name: Transfer Issue on Close

on:
  issues:
    types: [closed]

jobs:
  transfer_issue:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Transfer Issue
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        DESTINATION_REPO: 'austv-minecraft/servidor'
      run: |
        ISSUE_TITLE=$(jq -r '.issue.title' "$GITHUB_EVENT_PATH")
        ISSUE_BODY=$(jq -r '.issue.body' "$GITHUB_EVENT_PATH")
        ISSUE_URL=$(jq -r '.issue.html_url' "$GITHUB_EVENT_PATH")

        curl -X POST -H "Authorization: token $GITHUB_TOKEN" \
        -H "Accept: application/vnd.github.v3+json" \
        https://api.github.com/repos/$DESTINATION_REPO/issues \
        -d "{\"title\": \"${ISSUE_TITLE}\", \"body\": \"${ISSUE_BODY}\n\n[Original Issue](${ISSUE_URL})\"}"
